### ISSUE TITLE
User Change Password

### ISSUE THREAD

**Issue by atareshawty** [osumb/challenges#125]
I'll need to make a bunch of fake passwords, but users are going to want to change them

**Comment by tarebyte** [comment]
@atareshawty here are my thoughts:

- The user can change their password on the settings page. Example `/tareshawty.3/settings`
- The user should _have_ to change their password if they've never changed it before. We can setup a filter so that if the user is trying to do anything else, redirect them to the settings so that they change it. We'll need to add a database column for the state of the user, probably a boolean. Like `new_user` or something to that affect.

WDTY?

**Comment by atareshawty** [comment]
Makes sense to me. My plan was to have the accounts created and ready to go and just send an email with initial username/passwords. Forcing them to change their password on initial login would be excellent.

**Comment by atareshawty** [comment]
Unfortunately, I have no migration process or anything like that 😦. It's just been adding to `schema.sql` and running `npm run mock-data` to make the changes. Sorry about that one. This is like the first use case I've have for migrations
