### ISSUE TITLE
Better Job Scheduling

### ISSUE THREAD

**Issue by atareshawty** [osumb/challenges#199]
Node Scheduler keeps the job in memory. So when the server restarts, we lose the scheduled jobs. Heroku restarts it's dynos every 24 hours. The server(s) restart on deploys. Canceling jobs happens right now by just manually restarting the dynos.

I need a solution that:
- [ ] Can programmatically schedule jobs to send the challenge list email
- [ ] Can stay scheduled through things like node restarting/deploys
- [ ] Can manually be altered through UI/terminal (preferably UI)

**Comment by atareshawty** [comment]
Required reading: 
[clock.js example](https://github.com/johnhenry/example-heroku-clock-js)
[Heroku scheduling docs](https://devcenter.heroku.com/articles/scheduled-jobs-custom-clock-processes)

**Comment by atareshawty** [comment]
Here's what I'm thinking:

- Add a flag column to performances (called list_emailed) or something like that.
- Whenever Heroku restarts, have it run `clock: node schedule-challenge-list-email-job.js` (or something with a better name). We would just have to add that command to the Procfile
- The job scheduler would schedule a cron job that would find the most recent performance past the window and would send the email/create the empty results
- The job would run every 5 minutes between some hours and days that make sense

/cc @btmills What are your thoughts on this?

**Comment by btmills** [comment]
A possible alternative: Rather than creating a separate task that runs every 5 minutes and polls the database, schedule the email for whenever the window closes. That would be scheduled whenever the challenge window is created. On startup, look at the most recent challenge

- When a challenge window is created, schedule the email for whenever the email closes.

    ```js
    setTimeout(() => {
        sendEmailForChallenge(this.id);
    }, windowCloseTime - Date.now());
    ```

    Where that call happens is left as an exercise to the reader.

- On start, if a challenge window has closed but the email flag has not been set, send the email immediately. This covers the case where the process is not running when the window closes.
- On start, find any windows that have not yet closed. Schedule emails for window close.

Either approach will work, both are valid. It depends where you want your complexity.

**Comment by atareshawty** [comment]
The end goal is to be able to adapt to a challenge window being edited, which has already happened. To keep the one time scheduling, I'd have to keep track of some `jobId` and edit it if and when the performance window changes. I'm not sure if the jobs are accessible outside of the scrip that runs them, since they're stored in memory. I like only having the job run once per performance, but that would lose the flexibility of editing things. Four challenges in and I've learned that **everything** needs to be flexible and editable lol

**Comment by atareshawty** [comment]
Also, thanks for your input 🚀  Much appreciated!!

**Comment by btmills** [comment]
If editing the closing time is a possibility, and you don't feel particularly passionate about writing your own job scheduler, then yes, stay *far* **far** away from the second idea.
